In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
    'Salary': [45000, 54000, 50000, 62000, 47000]
}

df = pd.DataFrame(data)

In [3]:
df.head()

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

In [4]:
df.shape

(5, 4)

In [6]:
df.dtypes

Name          object
Age            int64
Department    object
Salary         int64
dtype: object

In [7]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  51600.000000
std     3.962323   6730.527468
min    22.000000  45000.000000
25%    24.000000  47000.000000
50%    27.000000  50000.000000
75%    29.000000  54000.000000
max    32.000000  62000.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [9]:
df.tail()

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

In [10]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='object')

In [ ]:
#summary statistics of age and salary
df[['Age', 'Salary']].describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  51600.000000
std     3.962323   6730.527468
min    22.000000  45000.000000
25%    24.000000  47000.000000
50%    27.000000  50000.000000
75%    29.000000  54000.000000
max    32.000000  62000.000000

In [14]:
hr_avg_salary = df[df['Department'] == 'HR']['Salary'].mean()
print("Average HR Salary:", hr_avg_salary)

Average HR Salary: 46000.0

In [ ]:
#  Add a new column 'Bonus' = 10% of Salary
df['Bonus'] = df['Salary'] * 0.10
print("DataFrame after adding Bonus column:")
print(df)

DataFrame after adding Bonus column:
      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

In [16]:
#  Filter employees aged between 25 and 30
age_filter = df[(df['Age'] >= 25) & (df['Age'] <= 30)]
print("\nEmployees aged between 25 and 30:")
print(age_filter)

Employees aged between 25 and 30:
  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

In [ ]:
# Group by Department and calculate average salary
dept_avg_salary = df.groupby('Department')['Salary'].mean()
print("\nAverage salary by department:")
print(dept_avg_salary)

Average salary by department:
Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

In [19]:
#Sort DataFrame by 'Salary' in ascending order and save to CSV
sorted_df = df.sort_values(by='Salary', ascending=True)
sorted_df.to_csv("sorted_employees.csv", index=False)

In [20]:

df.to_csv("Sorted DataFrame saved as 'sorted_employees.csv'")